// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BlazorTemplate.Migrations
{
    [DbContext(typeof(AppDataContext))]
    partial class AppDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BlazorTemplate.Data.WeatherForecast", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateTimeAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Summary")
                        .HasColumnType("text")
                        .HasColumnName("summary");

                    b.Property<int>("TemperatureC")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("forecasts", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateTimeAt = new DateTime(2023, 4, 3, 16, 40, 20, 551, DateTimeKind.Utc).AddTicks(1870),
                            Summary = "Cool",
                            TemperatureC = 54
                        },
                        new
                        {
                            Id = 2,
                            DateTimeAt = new DateTime(2023, 4, 4, 16, 40, 20, 551, DateTimeKind.Utc).AddTicks(1870),
                            Summary = "Freezing",
                            TemperatureC = 32
                        },
                        new
                        {
                            Id = 3,
                            DateTimeAt = new DateTime(2023, 4, 5, 16, 40, 20, 551, DateTimeKind.Utc).AddTicks(1870),
                            Summary = "Sweltering",
                            TemperatureC = 16
                        },
                        new
                        {
                            Id = 4,
                            DateTimeAt = new DateTime(2023, 4, 6, 16, 40, 20, 551, DateTimeKind.Utc).AddTicks(1870),
                            Summary = "Cool",
                            TemperatureC = -20
                        },
                        new
                        {
                            Id = 5,
                            DateTimeAt = new DateTime(2023, 4, 7, 16, 40, 20, 551, DateTimeKind.Utc).AddTicks(1870),
                            Summary = "Scorching",
                            TemperatureC = -2
                        },
                        new
                        {
                            Id = 6,
                            DateTimeAt = new DateTime(2023, 4, 8, 16, 40, 20, 551, DateTimeKind.Utc).AddTicks(1870),
                            Summary = "Hot",
                            TemperatureC = -4
                        },
                        new
                        {
                            Id = 7,
                            DateTimeAt = new DateTime(2023, 4, 9, 16, 40, 20, 551, DateTimeKind.Utc).AddTicks(1870),
                            Summary = "Freezing",
                            TemperatureC = -12
                        },
                        new
                        {
                            Id = 8,
                            DateTimeAt = new DateTime(2023, 4, 10, 16, 40, 20, 551, DateTimeKind.Utc).AddTicks(1870),
                            Summary = "Hot",
                            TemperatureC = 43
                        },
                        new
                        {
                            Id = 9,
                            DateTimeAt = new DateTime(2023, 4, 11, 16, 40, 20, 551, DateTimeKind.Utc).AddTicks(1870),
                            Summary = "Sweltering",
                            TemperatureC = -18
                        },
                        new
                        {
                            Id = 10,
                            DateTimeAt = new DateTime(2023, 4, 12, 16, 40, 20, 551, DateTimeKind.Utc).AddTicks(1870),
                            Summary = "Freezing",
                            TemperatureC = 27
                        },
                        new
                        {
                            Id = 11,
                            DateTimeAt = new DateTime(2023, 4, 13, 16, 40, 20, 551, DateTimeKind.Utc).AddTicks(1870),
                            Summary = "Warm",
                            TemperatureC = 12
                        },
                        new
                        {
                            Id = 12,
                            DateTimeAt = new DateTime(2023, 4, 14, 16, 40, 20, 551, DateTimeKind.Utc).AddTicks(1870),
                            Summary = "Hot",
                            TemperatureC = 36
                        },
                        new
                        {
                            Id = 13,
                            DateTimeAt = new DateTime(2023, 4, 15, 16, 40, 20, 551, DateTimeKind.Utc).AddTicks(1870),
                            Summary = "Mild",
                            TemperatureC = 39
                        },
                        new
                        {
                            Id = 14,
                            DateTimeAt = new DateTime(2023, 4, 16, 16, 40, 20, 551, DateTimeKind.Utc).AddTicks(1870),
                            Summary = "Balmy",
                            TemperatureC = 53
                        },
                        new
                        {
                            Id = 15,
                            DateTimeAt = new DateTime(2023, 4, 17, 16, 40, 20, 551, DateTimeKind.Utc).AddTicks(1870),
                            Summary = "Bracing",
                            TemperatureC = -17
                        },
                        new
                        {
                            Id = 16,
                            DateTimeAt = new DateTime(2023, 4, 18, 16, 40, 20, 551, DateTimeKind.Utc).AddTicks(1870),
                            Summary = "Warm",
                            TemperatureC = -14
                        },
                        new
                        {
                            Id = 17,
                            DateTimeAt = new DateTime(2023, 4, 19, 16, 40, 20, 551, DateTimeKind.Utc).AddTicks(1870),
                            Summary = "Warm",
                            TemperatureC = 11
                        },
                        new
                        {
                            Id = 18,
                            DateTimeAt = new DateTime(2023, 4, 20, 16, 40, 20, 551, DateTimeKind.Utc).AddTicks(1870),
                            Summary = "Scorching",
                            TemperatureC = 41
                        },
                        new
                        {
                            Id = 19,
                            DateTimeAt = new DateTime(2023, 4, 21, 16, 40, 20, 551, DateTimeKind.Utc).AddTicks(1870),
                            Summary = "Chilly",
                            TemperatureC = 5
                        },
                        new
                        {
                            Id = 20,
                            DateTimeAt = new DateTime(2023, 4, 22, 16, 40, 20, 551, DateTimeKind.Utc).AddTicks(1870),
                            Summary = "Scorching",
                            TemperatureC = 46
                        },
                        new
                        {
                            Id = 21,
                            DateTimeAt = new DateTime(2023, 4, 23, 16, 40, 20, 551, DateTimeKind.Utc).AddTicks(1870),
                            Summary = "Sweltering",
                            TemperatureC = 54
                        },
                        new
                        {
                            Id = 22,
                            DateTimeAt = new DateTime(2023, 4, 24, 16, 40, 20, 551, DateTimeKind.Utc).AddTicks(1870),
                            Summary = "Mild",
                            TemperatureC = 52
                        },
                        new
                        {
                            Id = 23,
                            DateTimeAt = new DateTime(2023, 4, 25, 16, 40, 20, 551, DateTimeKind.Utc).AddTicks(1870),
                            Summary = "Balmy",
                            TemperatureC = 33
                        },
                        new
                        {
                            Id = 24,
                            DateTimeAt = new DateTime(2023, 4, 26, 16, 40, 20, 551, DateTimeKind.Utc).AddTicks(1870),
                            Summary = "Freezing",
                            TemperatureC = -12
                        },
                        new
                        {
                            Id = 25,
                            DateTimeAt = new DateTime(2023, 4, 27, 16, 40, 20, 551, DateTimeKind.Utc).AddTicks(1870),
                            Summary = "Scorching",
                            TemperatureC = 41
                        },
                        new
                        {
                            Id = 26,
                            DateTimeAt = new DateTime(2023, 4, 28, 16, 40, 20, 551, DateTimeKind.Utc).AddTicks(1870),
                            Summary = "Chilly",
                            TemperatureC = -14
                        },
                        new
                        {
                            Id = 27,
                            DateTimeAt = new DateTime(2023, 4, 29, 16, 40, 20, 551, DateTimeKind.Utc).AddTicks(1870),
                            Summary = "Chilly",
                            TemperatureC = 23
                        },
                        new
                        {
                            Id = 28,
                            DateTimeAt = new DateTime(2023, 4, 30, 16, 40, 20, 551, DateTimeKind.Utc).AddTicks(1870),
                            Summary = "Cool",
                            TemperatureC = 44
                        },
                        new
                        {
                            Id = 29,
                            DateTimeAt = new DateTime(2023, 5, 1, 16, 40, 20, 551, DateTimeKind.Utc).AddTicks(1870),
                            Summary = "Cool",
                            TemperatureC = 7
                        },
                        new
                        {
                            Id = 30,
                            DateTimeAt = new DateTime(2023, 5, 2, 16, 40, 20, 551, DateTimeKind.Utc).AddTicks(1870),
                            Summary = "Hot",
                            TemperatureC = 40
                        },
                        new
                        {
                            Id = 31,
                            DateTimeAt = new DateTime(2023, 5, 3, 16, 40, 20, 551, DateTimeKind.Utc).AddTicks(1870),
                            Summary = "Hot",
                            TemperatureC = 15
                        },
                        new
                        {
                            Id = 32,
                            DateTimeAt = new DateTime(2023, 5, 4, 16, 40, 20, 551, DateTimeKind.Utc).AddTicks(1870),
                            Summary = "Balmy",
                            TemperatureC = -6
                        },
                        new
                        {
                            Id = 33,
                            DateTimeAt = new DateTime(2023, 5, 5, 16, 40, 20, 551, DateTimeKind.Utc).AddTicks(1870),
                            Summary = "Mild",
                            TemperatureC = 6
                        },
                        new
                        {
                            Id = 34,
                            DateTimeAt = new DateTime(2023, 5, 6, 16, 40, 20, 551, DateTimeKind.Utc).AddTicks(1870),
                            Summary = "Cool",
                            TemperatureC = -8
                        },
                        new
                        {
                            Id = 35,
                            DateTimeAt = new DateTime(2023, 5, 7, 16, 40, 20, 551, DateTimeKind.Utc).AddTicks(1870),
                            Summary = "Freezing",
                            TemperatureC = 4
                        },
                        new
                        {
                            Id = 36,
                            DateTimeAt = new DateTime(2023, 5, 8, 16, 40, 20, 551, DateTimeKind.Utc).AddTicks(1870),
                            Summary = "Warm",
                            TemperatureC = -15
                        },
                        new
                        {
                            Id = 37,
                            DateTimeAt = new DateTime(2023, 5, 9, 16, 40, 20, 551, DateTimeKind.Utc).AddTicks(1870),
                            Summary = "Scorching",
                            TemperatureC = 13
                        },
                        new
                        {
                            Id = 38,
                            DateTimeAt = new DateTime(2023, 5, 10, 16, 40, 20, 551, DateTimeKind.Utc).AddTicks(1870),
                            Summary = "Balmy",
                            TemperatureC = -1
                        },
                        new
                        {
                            Id = 39,
                            DateTimeAt = new DateTime(2023, 5, 11, 16, 40, 20, 551, DateTimeKind.Utc).AddTicks(1870),
                            Summary = "Sweltering",
                            TemperatureC = 23
                        },
                        new
                        {
                            Id = 40,
                            DateTimeAt = new DateTime(2023, 5, 12, 16, 40, 20, 551, DateTimeKind.Utc).AddTicks(1870),
                            Summary = "Scorching",
                            TemperatureC = -13
                        },
                        new
                        {
                            Id = 41,
                            DateTimeAt = new DateTime(2023, 5, 13, 16, 40, 20, 551, DateTimeKind.Utc).AddTicks(1870),
                            Summary = "Hot",
                            TemperatureC = 13
                        },
                        new
                        {
                            Id = 42,
                            DateTimeAt = new DateTime(2023, 5, 14, 16, 40, 20, 551, DateTimeKind.Utc).AddTicks(1870),
                            Summary = "Bracing",
                            TemperatureC = -3
                        },
                        new
                        {
                            Id = 43,
                            DateTimeAt = new DateTime(2023, 5, 15, 16, 40, 20, 551, DateTimeKind.Utc).AddTicks(1870),
                            Summary = "Warm",
                            TemperatureC = 40
                        },
                        new
                        {
                            Id = 44,
                            DateTimeAt = new DateTime(2023, 5, 16, 16, 40, 20, 551, DateTimeKind.Utc).AddTicks(1870),
                            Summary = "Freezing",
                            TemperatureC = -7
                        },
                        new
                        {
                            Id = 45,
                            DateTimeAt = new DateTime(2023, 5, 17, 16, 40, 20, 551, DateTimeKind.Utc).AddTicks(1870),
                            Summary = "Freezing",
                            TemperatureC = 37
                        },
                        new
                        {
                            Id = 46,
                            DateTimeAt = new DateTime(2023, 5, 18, 16, 40, 20, 551, DateTimeKind.Utc).AddTicks(1870),
                            Summary = "Warm",
                            TemperatureC = -12
                        },
                        new
                        {
                            Id = 47,
                            DateTimeAt = new DateTime(2023, 5, 19, 16, 40, 20, 551, DateTimeKind.Utc).AddTicks(1870),
                            Summary = "Sweltering",
                            TemperatureC = -6
                        },
                        new
                        {
                            Id = 48,
                            DateTimeAt = new DateTime(2023, 5, 20, 16, 40, 20, 551, DateTimeKind.Utc).AddTicks(1870),
                            Summary = "Chilly",
                            TemperatureC = 8
                        },
                        new
                        {
                            Id = 49,
                            DateTimeAt = new DateTime(2023, 5, 21, 16, 40, 20, 551, DateTimeKind.Utc).AddTicks(1870),
                            Summary = "Hot",
                            TemperatureC = 14
                        },
                        new
                        {
                            Id = 50,
                            DateTimeAt = new DateTime(2023, 5, 22, 16, 40, 20, 551, DateTimeKind.Utc).AddTicks(1870),
                            Summary = "Scorching",
                            TemperatureC = 49
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
